#! /bin/bash

# Android Utility
# Author: Tommy Nguyen [tommytoamtoe]
# Version: a-0.89
# Date: June 15, 2011
# Contact: tommytomatoe@gmail.com

#introduction
clear
echo "Welcome" $USER,
echo "Today is" `date`
echo

##functions
#enter
enter()
{	echo
	echo "Please press [enter] to continue";
	read -s -n 1 key
	if [[ $key = "" ]]; then 
  		echo
  		clear
	fi
}

#quit
quit()
{	echo
	echo "Thank you for choosing Android Utility"
	echo "brought to you by tommytomatoe :-)"
	echo
	echo "Please Don't Drink and Drive"
	echo
	exit
}

#future features
ff ()
{	clear
	echo "Feature coming in a future release. Stay tuned."
	enter
}


android () 
{
echo "   Android Utility by tommytomatoe"
echo "      ----------------------     "
echo "   Blue Waffle Magic Pack v a-0.89"
echo "|-------------------------------||-------------------------------|"
echo "|-------------------------------||-------------------------------|"
echo "|         BASIC TOOLS           ||         AWESOME SAUCE         |"
echo "|-------------------------------||-------------------------------|"
echo "| 1.  adb tools                 || 5.  apk Re-Engineering        |"
echo "| 2.  keystore manager          || 6.  smali and baksmali        |"
echo "| 3.                            || 7.  PNG optimize              |"
echo "| 4.                            || 8.  draw9patch utilities      |"
echo "|-------------------------------||-------------------------------|"
echo "|-------------------------------||-------------------------------|"
echo "|             SETUP             ||"
echo "|-------------------------------||"
echo "| x.  Run Installation Guide    ||"
echo "|-------------------------------||"
echo "|-------------------------------||"
echo "| q.  Quit                      ||"
echo "      ----------------------     "
printf %s "Select an Option: "
read num
case $num in
 1) clear; ttadb;;
 2) ff;;
 3) ff;;
 4) echo;;
 5) apk_tool;;
 6) ff;;
 x) installau;;
 q) quit;;
 *) echo; echo "$num is not a valid option"; enter;
esac
}

while :
do
	android
done
