#! /bin/bash

# Android Utility
# Author: Tommy Nguyen [tommytoamtoe]
# Version: b-0.89
# Date: July 08, 2011
# Contact: tommytomatoe@gmail.com

#introduction
intro ()
{
clear
echo "Welcome back" $USER,
echo
}

##functions
#enter
enter()
{	echo
	echo "Please press [enter] to continue";
	read -s -n 1 key
	if [[ $key = "" ]]; then 
  		echo
  		clear
	fi
}

#credits
credits ()
{	clear
	echo -n T
	sleep .1
	echo -n h
	sleep .1
	echo -n a
	sleep .1
	echo -n n
	sleep .1
	echo -n k 
	sleep .1	
	sleep .1
	echo -n " " 
	echo -n y
	sleep .1
	echo -n o
	sleep .1
	echo -n u
	sleep .1
	echo -n  " "
	sleep .1
	echo -n f
	sleep .1
	echo -n o
	sleep .1
	echo -n r
	sleep .1
	echo -n  " "
	sleep .1
	echo -n u
	sleep .1
	echo -n s
	sleep .1
	echo -n i
	sleep .1
	echo -n n
	sleep .1
	echo -n g
	sleep .1
	echo -n  " "
	sleep .1
	echo -n A
	sleep .1
	echo -n n
	sleep .1
	echo -n d
	sleep .1
	echo -n r
	sleep .1
	echo -n o
	sleep .1
	echo -n i
	sleep .1
	echo -n d
	sleep .1
	echo -n " "  
	sleep .1
	echo -n U
	sleep .1
	echo -n t
	sleep .1
	echo -n i
	sleep .1
	echo -n l
	sleep .1
	echo -n i
	sleep .1
	echo -n t
	sleep .1
	echo -n y
	sleep .1
	echo "."
	echo
	sleep .5
	echo -n "The"
	sleep .1
	echo -n " " 
	sleep .1
	echo -n goal 
	sleep .1
	echo -n " "
	sleep .1
	echo -n of 
	sleep .1
	echo -n " "
	sleep .1
	echo -n this 
	sleep .1
	echo -n " "
	sleep .1
	echo -n project 
	sleep .1
	echo -n " "
	sleep .1
	echo -n is 
	sleep .1
	echo -n " "
	sleep .1
	echo -n to 
	sleep .1
	echo -n " "
	sleep .1
	echo -n assist
	sleep .1
	echo -n " "
	sleep .1
	echo -n you,
	sleep .1
	echo -n " "
	sleep .1
	echo -n $USER, 
	sleep .1
	echo -n " "
	sleep .1
	echo -n in 
	sleep .1
	echo -n " "
	sleep .1
	echo -n android 
	sleep .1
	echo -n " "
	sleep .1
	echo development.
	echo
	sleep .5
	echo -n I 
	sleep .1
	sleep .1
	echo -n " "
	echo -n h
	sleep .1
	echo -n o
	sleep .1
	echo -n p
	sleep .1
	echo -n e
	sleep .1
	echo -n  
	sleep .1
	echo -n " "
	sleep .1
	echo -n t
	sleep .1
	echo -n h
	sleep .1
	echo -n e
	sleep .1
	echo -n s
	sleep .1
	echo -n e
	sleep .1
	echo -n  
	sleep .1
	echo -n " "
	sleep .1
	echo -n g
	sleep .1
	echo -n o
	sleep .1
	echo -n a
	sleep .1
	echo -n l
	sleep .1
	echo -n s
	sleep .1
	echo -n  
	sleep .1
	echo -n " "
	sleep .1
	echo -n a
	sleep .1
	echo -n r
	sleep .1
	echo -n e
	sleep .1
	echo -n  
	sleep .1
	echo -n " "
	sleep .1
	echo -n m
	sleep .1
	echo -n e
	sleep .1
	echo -n t
	sleep .1
	echo "."
	echo
	sleep .5
	echo "   ### Thanks and Credits ###"
	echo
	sleep .5
	echo "Brut.all - apktool.jar and sound advice"
	sleep .5
	echo "JesusFreke - baksmali.jar and smali.jar"
	sleep .5
	echo "Google - AOSP"
	sleep .5
	echo "aamikam - sound advice"
	sleep .5
	echo "themikmik.com - Awesome sauce"
	sleep .1
	echo "xda developers - Roots" 
	sleep .5
	echo "JsChiSurf - sound advice"
	sleep .5
	echo "dsixda - sound advice"
	sleep .5
	echo "Igor Pavlov - 7zip"
	sleep .5
	echo "Ardfry Imaging, LLC. - pngout"
	sleep .5
	echo -n T
	sleep .1
	echo -n o
	sleep .1
	echo -n m
	sleep .1
	echo -n m
	sleep .1
	echo -n y
	sleep .1
	echo -n " " 
	sleep .1
	echo -n N
	sleep .1
	echo -n g
	sleep .1
	echo -n u
	sleep .1
	echo -n y
	sleep .1
	echo -n e
	sleep .1
	echo -n n
	sleep .1
	echo -n " " 
	sleep .1
	echo -n -
	sleep .1
	echo -n " " 
	sleep .1
	echo -n A
	sleep .1
	echo -n n
	sleep .1
	echo -n d
	sleep .1
	echo -n r
	sleep .1
	echo -n o
	sleep .1
	echo -n i
	sleep .1
	echo -n d
	sleep .1
	echo -n  
	sleep .1
	echo -n " "
	sleep .1
	echo -n U
	sleep .1
	echo -n t
	sleep .1
	echo -n i
	sleep .1
	echo -n l
	sleep .1
	echo -n i
	sleep .1
	echo -n t
	sleep .1
	echo y
	sleep .1
	echo
	echo "You will only see this message once."
	enter
}
	
#quit
quit()
{	if ! [[ -a $z/resources/.2 ]] ; then
	touch $z/resources/.2
	credits
else
	echo
	echo "Thank you for choosing Android Utility"
	echo "brought to you by tommytomatoe :-)"
	echo
	echo "Please Don't Drink and Drive"
	echo
fi
	exit
}

#future features
ff ()
{	clear
	echo "Feature coming in a future release. Stay tuned."
	enter
}

#Welcome
welcome ()
{	clear
echo
echo -n "W"
sleep .1
echo -n "e"
sleep .1
echo -n "l"
sleep .1
echo -n "c"
sleep .1
echo -n "o"
sleep .1
echo -n "m"
sleep .1
echo -n "e"
sleep .1
echo -n " "
sleep .1
echo -n "t"
sleep .1
echo -n "o"
sleep .1
echo -n " "
sleep .2
echo -n "A"
sleep .1
echo -n "n"
sleep .1
echo -n "d"
sleep .1
echo -n "r"
sleep .1
echo -n "o"
sleep .1
echo -n "i"
sleep .2
echo -n "d"
sleep .1
echo -n " "
sleep .1
echo -n "U"
sleep .1
echo -n "t"
sleep .1
echo -n "i"
sleep .1
echo -n "l"
sleep .1
echo -n "i"
sleep .1
echo -n "t"
sleep .1
echo -n "y"
sleep .1
echo ","
sleep .2
echo 
sleep .1
echo -n "b"
sleep .1
echo -n "r"
sleep .25
echo -n "o"
sleep .1
echo -n "u"
sleep .1
echo -n "g"
sleep .1
echo -n "h"
sleep .1
echo -n "t"
sleep .1
echo -n " "
sleep .2
echo -n "t"
sleep .1
echo -n "o"
sleep .1
echo -n " "
sleep .1
echo -n "y"
sleep .1
echo -n "o"
sleep .1
echo -n "u"
sleep .1
echo -n " "
sleep .1
echo -n "b"
sleep .1
echo -n "y"
sleep .1
echo ":"
sleep .1
echo
echo -n "t"
sleep .2
echo -n "o"
sleep .1
echo -n "m"
sleep .2
echo -n "m"
sleep .1
echo -n "y"
sleep .1
echo -n "t"
sleep .1
echo -n "o"
sleep .1
echo -n "m"
sleep .2
echo -n "a"
sleep .1
echo -n "t"
sleep .1
echo -n "o"
sleep .1
echo "e"
echo
echo -n "e"
sleep .2
echo -n "n"
sleep .1
echo -n "j"
sleep .2
echo -n "o"
sleep .1
echo -n "y"
sleep .1
echo -n " "
sleep .1
echo -n "t"
sleep .1
echo -n "h"
sleep .2
echo -n "e"
sleep .1
echo -n " "
sleep .1
echo -n "p"
sleep .1
echo -n "o"
sleep .2
echo -n "s"
sleep .1
echo -n "s"
sleep .2
echo -n "i"
sleep .1
echo -n "b"
sleep .1
echo -n "i"
sleep .1
echo -n "l"
sleep .1
echo -n "i"
sleep .2
echo -n "t"
sleep .1
echo -n "i"
sleep .1
echo -n "e"
sleep .1
echo -n "s"
sleep .1
echo "."
echo
sleep .25
}

#load
load_dot ()
{	echo -n "."
	sleep .15
	echo -n "."
	sleep .15
	echo -n "."
	sleep .15
	echo -n "."
	sleep .15
	echo -n "."
	sleep .15
	echo "."
}

#System Check
check_s ()
{
w=$HOME/android-utility/
if ! [[ -s $w ]] ; then
	echo "Please place android-utility in the directory $HOME before preceding. Thank you very much"	
	enter
	check_s
else
	echo "Preparing to run the Installation Guide."
	echo -n "Please wait."
	load_dot
	echo
	echo "ALERT: You will only see this screen once."
	sleep .25
	enter
	$w/installau -f
fi
}
 

android () 
{
echo "   Android Utility by tommytomatoe"
echo "      ----------------------     "
echo "   Blue Waffle Magic Pack v b-0.89"
echo "|-------------------------------||-------------------------------|"
echo "|-------------------------------||-------------------------------|"
echo "|         BASIC TOOLS           ||         AWESOME SAUCE         |"
echo "|-------------------------------||-------------------------------|"
echo "| 1.  adb tools                 || 6.  apk Re-Engineering        |"
echo "| 2.  keystore manager          || 7.  smali and baksmali        |"
echo "| 3.  sign apk and update.zip   || 8.  PNG optimize              |"
echo "| 4.  zipalign                  || 9.  draw9patch utilities      |"
echo "| 5.  install SDK               ||                               |"
echo "|                               ||-------------------------------|"
echo "|                               ||             SETUP             |"
echo "|                               ||-------------------------------|"
echo "|                               || e.  Extras                    |"
echo "|-------------------------------|| x.  Run Installation Guide    |"
echo "|-------------------------------||-------------------------------|"
echo "| q.  Quit                      ||-------------------------------|"
echo "      ----------------------     "
printf %s "Select an Option: "
read num
case $num in
 1) clear; ttadb;;
 2) keys_sig;;
 3) zasign;;
 4) zipped_up;;
 5) ff;;
 6) apk_tool;;
 7) ff;;
 8) ff;;
 9) 9patch;;
 e|E) extras;;
 x) installau;;
 q) quit;;
 *) echo; echo "$num is not a valid option"; enter;
esac
}

z=$HOME/android-utility/
if ! [[ -a $z/resources/.1 ]] ; then
	touch $z/resources/.1
	welcome
	check_s
else
	intro
fi

while :
do
	android
done
