#! /bin/bash

clear

# Installation Script


# Functions

#enterKey
enterKey()
{	echo "### Press [enter] to continue, any other key to quit";
	read -s -n 1 key
	if [[ $key = "" ]]; then 
  		echo 
	else
  		echo
  		echo "Installation aborted";
		enter
		inst
	fi
}

#enter
enter()
{	echo
	echo "Please press [enter] to continue";
	read -s -n 1 key
	if [[ $key = "" ]]; then 
  		echo
  		clear
	fi
}

#export PATH
export_PATH ()
{	cd $HOME/android-utility/
	PATH="$PATH:$PWD/utility"
	export PATH
	echo "$PATH"
	echo
}

#make directories
makedir ()
{	w=$HOME/android-utility/working-folder
	if [[ -s $h/$w ]] ; then
		echo
		echo "Working folder exists, would you like to start over? [Y/n] [default=Y]"
		read -s -n 1 ans
		case $ans in 
		n|N) echo; echo "Working folder remained unchanged"; enter;;
		*) echo; echo "Working folder replaced "; makedirA; enter;;
		esac
	else
		makedirB
	fi
		
}

makedirA ()
{	rm -r $HOME/android-utility/working-folder
	mkdir $HOME/android-utility/working-folder
	mkdir $w/0.mod-multiple-apk
	mkdir $w/0.mod-single-apk
	mkdir $w/2.png-opt
	mkdir $w/2.ninepatch-decompiler
	mkdir $w/2.ninepatch-compiler
	}

makedirB ()
{	mkdir $HOME/android-utility/working-folder
	mkdir $w/0.mod-multiple-apk
	mkdir $w/0.mod-single-apk
	mkdir $w/2.png-opt
	mkdir $w/2.ninepatch-decompiler
	mkdir $w/2.ninepatch-compiler
	enter
	}

#quit
quit()
{	echo
	echo "Thank you for choosing Android Utility"
	echo "brought to you by tommytomatoe :-)"
	echo
	echo "Please Don't Drink and Drive"
	echo
	exit
}

#select
selection ()
{	echo
	echo "You've selcted [$COM]"
	echo
}

## INSTALLS

first_time ()
{	COM="First Time Install"
	selection
	enterKey
	export_PATH
	echo "Adding executable permission to resources"
	chmod 755 resources/clean/*
	echo
	echo "Adding resources to usr/local/bin"
	echo
	sudo cp resources/clean/aapt-9 /usr/local/bin/aapt
	sudo cp resources/clean/adb /usr/local/bin/adb
    sudo cp resources/clean/andutil /usr/local/bin/
	sudo cp resources/clean/apktool /usr/local/bin/
	sudo cp resources/clean/apktool-1.4.1.jar /usr/local/bin/apktool.jar
	sudo cp resources/clean/baksmali /usr/local/bin/
	sudo cp resources/clean/baksmali.jar /usr/local/bin/
	sudo cp resources/clean/decode9patchPng.jar /usr/local/bin/
	sudo cp resources/clean/smali /usr/local/bin/
	sudo cp resources/clean/smali.jar /usr/local/bin/
	echo "Fixing permissions"
	sudo chmod 755 /usr/local/bin/*
	makedir
}

ins_apktool ()
{	COM="Install new apktool"
	selection
	enterKey
	clear
	echo "Your current verion of apktool is listed as:"
	echo
	echo "### `apktool | sed -n 1p`"
	echo
	echo "Which version of apktool would you like to install?"
	echo
	echo "  1.  apktool 1.3.1"
	echo "  2.  apktool 1.3.2"
	echo "  3.  apktool 1.4.1"
	echo
	printf "Please make your selection: "
	read sel
	case $sel in
	 1) sudo cp $HOME/android-utility/resources/apktool1.3.1/apktool.jar /usr/local/bin/;;
	 2) sudo cp $HOME/android-utility/resources/apktool1.3.2/apktool.jar /usr/local/bin/;;
	 3) sudo cp $HOME/android-utility/resources/apktool1.4.1/apktool.jar /usr/local/bin/;;
	 *) echo; echo "$sel is not a valid option"; echo;;	
	esac
	echo
	echo "Your version of apktool is now:"
	echo
	echo "### `apktool | sed -n 1p`"
	enter
	}
	
ins_aapt ()
{	COM="Install new aapt"
	selection
	enterKey
	clear
	echo "Which version of aapt would you like to install?"
	echo
	echo "  1.  aapt sdk  8 - Froyo Development"
	echo "  2.  aapt sdk  9 - Gingerbread Development"
	echo "  3.  aapt sdk 10 - Honeycomb Development"
	echo
	printf "Please make your selection: "
	read sel
	case $sel in
	 1) sudo cp $HOME/android-utility/resources/aapt/aapt-8 /usr/local/bin/aapt;;
	 2) sudo cp $HOME/android-utility/resources/aapt/aapt-9 /usr/local/bin/aapt;;
	 3) sudo cp $HOME/android-utility/resources/aapt/aapt-10 /usr/local/bin/aapt;;
	 *) echo; echo "$sel is not a valid option"; echo;;	
	esac
	echo
	echo "Your version of aapt has been updated"
	enter
	}
	
ins_addon ()
{	COM="Install new add-ons"
	selection
	enterKey
	clear
	echo "Option coming in a future release. Stay tuned."
	enter
	}
	

inst () 
{
echo "     -----------------------     "
echo "|     Android Utility v0.0.1    |"
echo "|      Installaltion Guide      |"
echo "|-------------------------------|"
echo "|-------------------------------|"
echo "| 1.  First Time Install        |"
echo "|-------------------------------|"
echo "| 2.  Install new apktool       |"
echo "| 3.  Install new aapt          |"
echo "| 4.  Install new add-ons       |"
echo "| 5.  Install Working Folder    |"
echo "|-------------------------------|"
echo "| x.  Run Android Utility       |"
echo "|-------------------------------|"
echo "|-------------------------------|"
echo "| q.  Quit Installation Guide   |"
echo "     -----------------------     "
printf %s "  Please Select Install: "
read num
case $num in
 1) first_time;;
 2) ins_apktool;;
 3) ins_aapt;;
 4) ins_addon;;
 5) makedir;;
 x) andutil;;
 q) quit;;
 *) echo; echo "$num is not a valid option"; enter;
esac
}

while :
do
	inst
done