#! /bin/bash

# Android Utility Linux
# Author: Tommy Nguyen [tommytomatoe]
# Version: 1.1.0
# Date: February 13, 2012
# Contact: tommytomatoe@gmail.com

# cheap wrapper for andutil - will work on better shortly
andutil
