#! /bin/bash

# Android Utility Linux
# Author: Tommy Nguyen [tommytomatoe]
# Version: 1.0.8
# Date: October 6, 2011
# Contact: tommytomatoe@gmail.com

#introduction
intro ()
{
clear
echo "Welcome back" $USER,
echo
}

##functions
#enter
enter()
{	echo
	echo "Please press [enter] to continue";
	read -s -n 1 key
	if [[ $key = "" ]]; then 
  		echo
  		clear
	fi
}

#credits
credits ()
{	clear
	echo "   ### Thanks and Credits ###"
	echo
	sleep .5
	echo "Brut.all - apktool.jar and sound advice"
	sleep .5
	echo "JesusFreke - baksmali.jar and smali.jar"
	sleep .5
	echo "Stericson/JF - testsign.jar"
	sleep .5
	echo "Pendo - sound advice/answering questions/awesome sauce"
	sleep .5
	echo "Google - AOSP"
	sleep .5
	echo "aamikam - sound advice"
	sleep .5
	echo "themikmik.com - Awesome sauce"
	sleep .1
	echo "xda developers - Roots" 
	sleep .5
	echo "JsChiSurf - sound advice"
	sleep .5
	echo "dsixda - sound advice"
	sleep .5
	echo "Amon_RA - sound advice"
	sleep .5
	echo "Igor Pavlov - 7zip"
	sleep .5
	echo "Ardfry Imaging, LLC. - pngout"
	sleep .5
	echo "Glenn Randers-Pehrson - pngcrush"
	sleep .5
	echo "Andrea Mazzoleni - advpng"
	sleep .5
	echo "Cosmin Truta - optipng"
	sleep .5
	echo "pxb1...@gmail.com - dex2jar"
	sleep .5
	echo "Emmanuel Dupuy - JD-GUI"
	sleep .5
	echo "misfit and leoisright - constant support"
	sleep .5
	echo "Xclusive Rydah, Chingy - testing and ideas"
	sleep .5
	echo
	echo -n T
	sleep .1
	echo -n o
	sleep .1
	echo -n m
	sleep .1
	echo -n m
	sleep .1
	echo -n y
	sleep .1
	echo -n " " 
	sleep .1
	echo -n N
	sleep .1
	echo -n g
	sleep .1
	echo -n u
	sleep .1
	echo -n y
	sleep .1
	echo -n e
	sleep .1
	echo -n n
	sleep .1
	echo -n " " 
	sleep .1
	echo -n -
	sleep .1
	echo -n " " 
	sleep .1
	for l in A n d r o i d ; do
	echo -n $l
	sleep .1
	done
	echo -n " "
	sleep .2
	for l in U t i l i t y ; do
	echo -n $l
	sleep .1
	done
	echo
	echo
	for l in T h a n k ; do
	echo -n $l
	sleep .1
	done
	sleep .1	
	sleep .1
	echo -n " " 
	for l in y o u ; do
	echo -n $l
	sleep .1
	done
	echo -n  " "
	sleep .1
	for l in f o r ; do
	echo -n $l
	sleep .1
	done
	echo -n  " "
	sleep .1
	for l in u s i n g ; do
	echo -n $l
	sleep .1
	done
	echo -n  " "
	sleep .1
	for l in A n d r o i d ; do
	echo -n $l
	sleep .1
	done
	echo -n " "
	sleep .2
	for l in U t i l i t y ; do
	echo -n $l
	sleep .1	
	done
	echo
	sleep .5
	echo "ALERT: You will only see this message once."
	enter
}
	
#quit
quit()
{	if ! [[ -a $z/resources/.2 ]] ; then
	touch $z/resources/.2
	credits
else
	echo
	echo "Thank you for choosing Android Utility"
	echo "brought to you by tommytomatoe :-)"
	echo
	echo "Please Don't Drink and Drive"
	echo
fi
	exit
}

#future features
ff ()
{	clear
	echo "Feature coming in a future release. Stay tuned."
	enter
}

#Welcome
welcome ()
{	clear
echo
for l in W e l c o m e ; do
echo -n $l
sleep .1
done
echo -n " "
sleep .1
for l in t o ; do
echo -n $l
sleep .1
done
echo -n " "
sleep .2
for l in A n d r o i d ; do
echo -n $l
sleep .1
done
echo -n " "
sleep .2
for l in U t i l i t y ; do
echo -n $l
sleep .1
done
sleep .1
echo ","
sleep .2
echo 
sleep .1
for l in b r o u g h t ; do
echo -n $l
sleep .1
done
echo -n " "
sleep .2
for l in t o ; do
echo -n $l
sleep .1
done
echo -n " "
sleep .1
for l in y o u ; do
echo -n $l
sleep .1
done
echo -n " "
sleep .1
for l in b y ; do
echo -n $l
sleep .1
done
sleep .1
echo ":"
sleep .1
echo
for l in t o m m y t o m a t o e ; do
echo -n $l
sleep .1
done
echo
echo
for l in e n j o y ; do
echo -n $l
sleep .1
done
echo -n " "
sleep .1
for l in t h e ; do
echo -n $l
sleep .1
done
echo -n " "
sleep .1
for l in p o s s i b i l i t i e s ; do
echo -n $l
sleep .1
done
echo "."
echo
sleep .25
}

#load
load_dot ()
{	for DOT in . . . . . . . ; do
	echo -n "$DOT"
	sleep .15
	done
	echo "."
}

#System Check
check_s ()
{
w=$HOME/android-utility/
if ! [[ -s $w ]] ; then
	echo "Please place android-utility in the directory $HOME before preceding. Thank you very much"	
	enter
	check_s
else
	echo "Preparing to run the Installation Guide."
	echo -n "Please wait."
	load_dot
	echo
	echo "ALERT: You will only see this screen once."
	sleep .25
	enter
	$w/installau -f
fi
}

odex_script ()
{	clear
	echo "Please be aware that this option has only"
	echo "been tested on the HTC EVO 3D Shooter"
	echo
	echo "Might be compatible with other Sense 3.0 Gingerbread Roms and Devices"
	echo "Please use with caution..."
	enter
	3vodex
}

kitchen_sink ()
{	clear
	echo "Preaparing to run dsixda's Android Kitchen"
	echo
	k=$HOME/android-utility/kitchen
	if ! [[ -s $k ]] ; then
		echo "Kitchen does not Exist, preparing to run git clone"
		git clone git://github.com/dsixda/Android-Kitchen.git $k
	else	
		echo -n "Kitchen Exists"
	fi
	load_dot
	cd $k
	./menu
}
 

android () 
{
which andutil $>/dev/null
if [[ "$?" -ne "0" ]] ; then
	source /etc/profile.d/au.sh
fi
echo "  Android Utility by tommytomatoe. Version $VERSION. Special Edition"
echo
echo "|-------------------------------||-------------------------------|"
echo "|-------------------------------||-------------------------------|"
echo "|         BASIC TOOLS           ||         ADVANCE TOOLS         |"
echo "|-------------------------------||-------------------------------|"
echo "| 1.  adb tools                 || 6.  apk Re-Engineering        |"
echo "| 2.  keystore manager          || 7.  apk Optimization          |"
echo "| 3.  sign apk and update.zip   || 8.  dex code utility          |"
echo "| 4.  zipalign                  || 9.  draw9patch utilities      |"
echo "| 5.  change-log creator        ||10.  AU ROM Utility            |"
echo "|                               ||11.  3vodex                    |"
echo "|-------------------------------||-------------------------------|"
echo "|                 K. Run dsixda's Android Kitchen                |"
echo "|----------------------------------------------------------------|"
echo "|----------------------------------------------------------------|"
echo "| x.  Run Installation Guide    || e.  Extras                    |"
echo "| i.  Install Android SDK       || q.  Quit                      |"
echo "| u.  Update Android-Utility    ||                               |"
echo "|-------------------------------||-------------------------------|"
printf %s " Select an Option: "
read num
case $num in
 1) clear; ttadb;;
 2) keys_sig;;
 3) zasign;;
 4) zipped_up;;
 5) change_log;;
 6) apk_tool;;
 7) apk_opt;;
 8) smali_tool;;
 9) 9patch;;
10) romutil;;
11) odex_script;;
 e|E) extras;;
 i|I) ff;;
 k|K) kitchen_sink;;
 x) installau;;
 u|U) clear; au-updater; enter;;
 q) quit;;
 *) echo; echo "$num is not a valid option"; enter;
esac
}

VERSION=`grep Version: $HOME/android-utility/README | sed 's:Version\:\ ::g'`
z=$HOME/android-utility/
if ! [[ -a $z/resources/.3 ]] ; then
	echo "Auto-update is turned on - recommended"
	echo "To turn off Auto-update, go to Extras"
	echo
	au-updater
fi

if ! [[ -a $z/resources/.1 ]] ; then
	touch $z/resources/.1
	welcome
	check_s
else
	intro
fi

while :
do
	android
done
