#!/bin/bash
# tommytomatoe customs
# Please use with care and read all instructions. 

#enter
enter()
{	echo
	echo "Please press [enter] to continue";
	read -s -n 1 key
	if [[ $key = "" ]]; then 
  		echo
  		clear
	fi
}

enter2()
{	echo
	echo "Please press [enter] to continue";
	read -s -n 1 key
	if [[ $key = "" ]]; then 
  		echo
	fi
}

remove_dex_framework()
{	echo
	echo "Making Directories"
	for fold in "$w/0-Original-FW" "$w/0-Minus-Dex-FW" "$w/0-FW-odex" ; do
		if ! [[ -d $fold ]] ; then
			mkdir $fold
		fi
	done
	echo 
	echo "Setting Variables"
	a=$w/framework
	b=$w/0-Original-FW
	c=$w/0-Minus-Dex-FW
	d=$w/0-FW-odex
	echo 
	cd $a
	for j in *jar ; do 
		cp $j $b/$j
		cp $j $c/$j
	done
	for o in *odex ; do
		cp $o $d/$o	
	done	
	cd $HOME
	cd $c
	for z in *.jar ; do 
		echo "Deleting dex from $z"
		aapt r -v $z classes.dex
	done
	enter
}

remove_dex_app()
{	echo
 	echo "Making Directories"
	for fold in "$w/0-Original-APP" "$w/0-Minus-Dex-APP" "$w/0-APP-odex" ; do
		if ! [[ -d $fold ]] ; then
			mkdir $fold
		fi
	done
	echo
	echo "Setting Variables"
	a=$w/app
	b=$w/0-Original-APP
	c=$w/0-Minus-Dex-APP
	d=$w/0-APP-odex
	echo 
	cd $a
	for app in *apk ; do 
		cp $app $b/$app
		cp $app $c/$app
	done
	for o in *odex ; do
		cp $o $d/$o
	done
	cd $HOME
	cd $c
	for z in *.apk ; do 
		echo "Deleting dex from $z"
		aapt r -v $z classes.dex
	done
	enter
}

remove_dex_data()
{	echo
 	echo "Making Directories"
  	for fold in "$w/0-Original-DATA" "$w/0-Minus-Dex-DATA" "$w/0-DATA-odex" ; do
		if ! [[ -d $fold ]] ; then
			mkdir $fold
		fi
	done
	echo
	echo "Setting Variables"
	a=$w/data-app
	b=$w/0-Original-DATA
	c=$w/0-Minus-Dex-DATA  
	d=$w/0-DATA-odex
	echo	
	cd $a
	for app in *apk ; do 
		cp $app $b/$app
		cp $app $c/$app
	done
	for o in *odex ; do
		cp $o $d/$o
	done
	cd $HOME
	cd $c
	for z in *.apk ; do 
		echo "Deleting dex from $z"
		aapt r -v $z classes.dex
	done
	enter
}

makedir ()
{	clear
	if ! [[ -s $w ]] ; then
		makedirA
	fi
}	

makedirA ()
{	echo 
	echo "Creating New Dex Directory"
	for folder in $w $w/app $w/data-app $w/framework ; do
		if ! [[ -s $folder ]] ; then
			mkdir $folder
		fi
	done
	echo 
	clear
}

tt_dex_rm ()
{	clear
	w=$HOME/android-utility/working-folder/odex
	makedir
	echo
	echo "               ***"	
	echo
	echo "Welcome to the Auto Dex-Removal Utility"
	echo "Version 0.1.0 aapt"
	echo
	echo "#  Place apps in working-folder/oex/app"
	echo "#  Place jars in working-folder/oex/framework"
	echo "#  If using 3vodex, your files were automatically pulled for you"
	echo
	echo "   Please Choose Option"
	echo
	echo "   a. dexrm for framework"
	echo "   b. dexrm for app"
	echo "   c. dexrm for app and framework"
	echo "   d. dexrm for data/app"
	echo "   q. quit program"
	echo 
	echo "   brought to you by"
	echo "   tommytomatoe" 
	echo
	echo "               ***"
	echo
		printf %s "Choose an Option: "
	read num
	case $num in
	t|T) makedir;;
	a|A) remove_dex_framework;;
	b|B) remove_dex_app;;
	c|C) remove_dex_framework; remove_dex_app;;
	d|D) remove_dex_data;;
	q|Q) echo; echo "Goodbye. Thank you for using, $USER."; echo; exit;
	esac
}

while :
do
tt_dex_rm
done


       	

  
