#!/bin/bash
# tommytomatoe customs
# Please use with care and read all instructions. 

#enter
enter()
{	echo
	echo "Please press [enter] to continue";
	read -s -n 1 key
	if [[ $key = "" ]]; then 
  		echo
  		clear
	fi
}

enter2()
{	echo
	echo "Please press [enter] to continue";
	read -s -n 1 key
	if [[ $key = "" ]]; then 
  		echo
	fi
}

remove_dex_framework()
{ echo
  echo "Making Directories"
  for fold in "$HOME/Dex/0-Original-FW" "$HOME/Dex/0-Minus-Dex-FW" "$HOME/Dex/0-FW-odex" ; do
	if [[ -d $fold ]] ; then
	rm -r $fold
	mkdir $fold
	else
	mkdir $fold
	fi
	done
echo 
echo "Setting Variables"
a=$HOME/Dex/framework/
b=$HOME/Dex/0-Original-FW/
c=$HOME/Dex/0-Minus-Dex-FW/  
d=$HOME/Dex/0-FW-odex/
echo ""	
cd $a
for j in *jar
	do 
		cp $j $HOME/Dex/0-Original-FW/$j
		cp $j $HOME/Dex/0-Minus-Dex-FW/$j
	done
for o in *odex
	do
		cp $o $HOME/Dex/0-FW-odex/$o	
	done	
cd $HOME
cd $c
for z in *.jar
	do 
		echo "Deleting dex from $z"
		aapt r -v $z classes.dex
	done
enter
}

remove_dex_app()
{ echo
  echo "Making Directories"
  for fold in "$HOME/Dex/0-Original-APP" "$HOME/Dex/0-Minus-Dex-APP" "$HOME/Dex/0-APP-odex" ; do
	if [[ -d $fold ]] ; then
	rm -r $fold
	mkdir $fold
	else
	mkdir $fold
	fi
	done
echo
echo "Setting Variables"
a=$HOME/Dex/app/
b=$HOME/Dex/0-Original-APP/
c=$HOME/Dex/0-Minus-Dex-APP/  
d=$HOME/Dex/0-App-odex/
echo ""	
cd $a
for a in *apk
	do 
		cp $a $HOME/Dex/0-Original-APP/$a
		cp $a $HOME/Dex/0-Minus-Dex-APP/$a
	done
for o in *odex
	do
		cp $o $HOME/Dex/0-App-odex/$o
	done
cd $HOME
cd $c
for z in *.apk
	do 
		echo "Deleting dex from $z"
		aapt r -v $z classes.dex
	done
enter
}

remove_dex_data()
{ echo
  echo "Making Directories"
  for fold in "$HOME/Dex/0-Original-DATA" "$HOME/Dex/0-Minus-Dex-DATA" "$HOME/Dex/0-DATA-odex" ; do
	if [[ -d $fold ]] ; then
	rm -r $fold
	mkdir $fold
	else
	mkdir $fold
	fi
	done
echo
echo "Setting Variables"
a=$HOME/Dex/data/
b=$HOME/Dex/0-Original-DATA/
c=$HOME/Dex/0-Minus-Dex-DATA/  
d=$HOME/Dex/0-DATA-odex/
echo ""	
cd $a
for a in *apk
	do 
		cp $a $HOME/Dex/0-Original-DATA/$a
		cp $a $HOME/Dex/0-Minus-Dex-DATA/$a
	done
for o in *odex
	do
		cp $o $HOME/Dex/0-DATA-odex/$o
	done
cd $HOME
cd $c
for z in *.apk
	do 
		echo "Deleting dex from $z"
		aapt r -v $z classes.dex
	done
enter
}

makedir ()
{	clear
	w=$HOME/Dex
	if [[ -s $w ]] ; then
		echo
		echo "Dex Folder exists, would you like to start over? [Y/n] [default=N]"
		read -s -n 1 ans
		case $ans in 
		y|Y) echo; makedirA; echo "Dex Folder replaced "; enter;;
		*) echo; echo "Dex Folder remained unchanged"; enter;;
		esac
	else
		makedirA
	fi
	z=$HOME/bin
	if [[ -s $z ]] ; then
		echo
		echo "$z exists, would you like to start over? [Y/n] [default=N]"
		read -s -n 1 ans
		case $ans in 
		y|Y) echo; mkdir $z; echo "$z replaced "; enter;;
		*) echo; echo "$z remained unchanged"; enter;;
		esac
	else
		mkdir $z
	fi
}	

makedirA ()
{	y=$HOME/Dex/
	echo 
	echo "Creating New Dex Directory"
	enter
	mkdir $y
	mkdir $y/app
	mkdir $y/data
	mkdir $y/framework
	echo 
	clear
}

tt_dex_rm ()
{	clear
	echo
	echo "               ***"	
	echo
	echo "Welcome to the Auto Dex-Removal Utility"
	echo "Version 0.0.2 aapt"
	echo
	echo "Instructions [Please Read all before starting]:"
	echo
	echo "1. Press [t] key to RUN FIRST"
	echo "2. Place apps and framework files in"
	echo "   in $HOME/Dex/"
	echo "3. Choose Options a, b, or c"
	enter	
	echo "1. Press [t] key to RUN FIRST"
	echo "2. Place apps and framework files in"
	echo "   in $HOME/Dex/"
	echo "3. Choose Options a, b, or c"
	echo
	echo "   Please Choose Option"
	echo
	echo "   t. RUN FIRST"
	echo "   a. dexrm for framework"
	echo "   b. dexrm for app"
	echo "   c. dexrm for all in one"
	echo "   d. dexrm for data/app"
	echo "   q. quit program"
	echo ""
	echo "   brought to you by"
	echo "   tommytomatoe"
	echo ""
	echo "   enjoy the possibilities..." 
	echo
	echo "               ***"
	echo
		printf %s "Choose an Option: "
	read num
	case $num in
	t|T) makedir;;
	a|A) remove_dex_framework;;
	b|B) remove_dex_app;;
	c|C) remove_dex_framework; remove_dex_app;;
	d|D) remove_dex_data;;
	q|Q) echo; echo "Goodbye. Thank you for using, $USER."; echo; exit;
	esac
}

while :
do
tt_dex_rm
done


       	

  
