#! /bin/bash

# ADB Express Script
# Author: Tommy Nguyen [tommytoamtoe]
# Version: b-0.89
# Date: July 05, 2011
# Contact: tommytomatoe@gmail.com

echo "Express Commands are to be used in conjunction with "mod-here-solo" folder, where only one file (apk, jar, et cetera) should be present at a time."
enter

##FUNCTIONS

#enterKey
enterKey()
{	echo "Press [enter] or [space] to $COM, any other key to quit";
	read -s -n 1 key
	if [[ $key = "" ]]; then 
  		echo "Initiating..."
		echo
	else
  		echo "Command not executed";
		enter
	fi
}

#enter
enter()
{	echo "Please press [enter] to continue";
	read -s -n 1 key
	if [[ $key = "" ]]; then 
  		adb_e
	fi
}

#error
error()
{	echo "## Error while processing command"
	echo
}

#error1
error1()
{	echo "## Error while processing command: Please specify valid file name or directory"
	echo
}

#User Decline
user_d()
{	echo "## Error while processing command: User declined"
	echo
}

#load
load()
{	echo -n "   ."
	sleep .125
	echo -n ".."
	sleep .125
	echo -n ".."
	sleep .125
	echo ".."
	sleep .125
	echo -n "    ."
	sleep .125
	echo -n ".."
	sleep .125
	echo -n ".."
	sleep .125
	echo ".."
	sleep .125
	echo -n "     ."
	sleep .125
	echo -n ".."
	sleep .125
	echo -n ".."
	sleep .125
	echo ".."
	sleep .125
}

#load back
daol()
{	echo -n "    ."
	sleep .125
	echo -n ".."
	sleep .125
	echo -n ".."
	sleep .125
	echo ".."
	sleep .125
}

#loader
loader()
{	daol
	load	
	daol
	load
	daol
	load
	daol
	load
	daol
	load
	daol
	load
	daol
	echo
	sleep .5
	echo "    ......."
	echo
	sleep .5
	echo "     ....."
	echo
	sleep .5
	echo "      ..."
	echo
	sleep .5
	echo "       ."
}


#adb pull express
adb_pull_e()
{	clear
	COM="adb pull"
	enterKey
	echo "adb pull..."
	printf "which /directory/filename? [ie. /system/app/Rosie.apk] = "
	read DIRNAM
	echo
	NAM=`basename $DIRNAM`
	for a in "adb pull $DIRNAM $e"
	do
	if [ -e "$e$NAM" ] ; then
		echo "Overwrite existing $NAM? [Y/n] [deafult=Y]"
		echo
		read -s -n 1 ans
		case "$ans" in
		y|Y) $a;;
		n|N) user_d;;
		*) $a;;
		esac
	else
		$a
	fi
	done
	enter
}

#adb push express
adb_push_e ()
{	clear
	COM="adb push"
	a=*
	enterKey
	printf %s "[adb push] to which directory? [ie. /system/app/] = "
	read DIR
	echo
	echo "This file is available in `basename $e`:"
	echo
	ls -t -1 $e
	echo
	echo "Confirm [adb push] of `ls -t -1 $e` to $DIR? [default=Yes]"
	echo
	echo "  1. Yes"
	echo "  2. No"
	read -s -n 1 ans
	case $ans in
	1) adb push $e$a $DIR;;
	2) echo; user_d;;
	*) adb push $e$a $DIR;;
	esac
	enter
}

#adb install express
adb_inst_e ()
{	clear
	COM="adb install"
	a=*.apk
	enterKey
	echo "This file is available in `basename $e`:"
	echo
	ls -t -1 $e
	echo
	echo "Confirm [install] of `ls -t -1 $e`? [default=Yes]"
	echo
	echo "  1. Yes"
	echo "  2. No"
	read -s -n 1 ans
	case $ans in
	1) adb install $e$a;;
	2) echo; user_d;;
	*) adb install $e$a;;
	esac
	enter
}

	


#express menu
adb_e ()
{	
e="$HOME/android-utility/working-folder/mod-here-solo/"
echo
clear
echo "     -----------------------     "
echo "|      Android Debug Bridge     |"
echo "|        Express Commands       |"
echo "|-------------------------------|"
echo "|-------------------------------|"
echo "| 1.  adb pull express          |"
echo "| 2.  adb push express          |"
echo "| 3.  install express           |"
echo "|-------------------------------|"
echo "|-------------------------------|"
echo "| q.  Go back to Main Menu      |"
echo "     -----------------------     "
printf "%s" "  Choose an ADB Command: "
read num
case "$num" in
  1)  adb_pull_e;;
  2)  adb_push_e;;
  3)  adb_inst_e;;
  q)  clear; exit;;
  *) echo; echo "Please enter valid option"; enter;
esac
}

while :
do
	adb_e
done