#! /bin/bash

# Extras Script
# Author: Tommy Nguyen [tommytomatoe]
# Version: b-1.0.0
# Date: July 08, 2011
# Contact: tommytomatoe@gmail.com

##FUNCTIONS

#load
load_dot ()
{	echo -n "."
	sleep .15
	echo -n "."
	sleep .15
	echo -n "."
	sleep .15
	echo -n "."
	sleep .15
	echo -n "."
	sleep .15
	echo "."
}

#enterKey
enterKey()
{	echo "Press [enter] or [space] to $COM, any other key to quit";
	read -s -n 1 key
	if [[ $key = "" ]]; then 
  		echo "Initiating..."
		echo
	else
  		echo "Command not executed";
		enter
	fi
}

#enter
enter()
{	echo "Please press [enter] to continue";
	read -s -n 1 key
	if [[ $key = "" ]]; then 
  		echo
	fi
}

#future features
ff ()
{	clear
	echo "Feature coming in a future release. Stay tuned."
	enter
}

#updates
check_u ()
{	echo "You have chosen to check for Updates"
	echo
	load_dot
	echo
	echo "Your current Version is $VERS."
	echo "This is an archaic way to do this. So please bear with me."
	echo
	echo "Just compare your version number with the latest in the github repo README."
	echo "Thank you. Pressing ENTER will take you to the repository."
	echo
	enter
	firefox https://github.com/tommytomatoe/Android-Utility
}

#contacts
contact_t ()
{	echo "Feel free to contact the author, tommytomamtoe, at the listed email addresses"
	echo
	echo "tommytomatoe@gmail.com"
	echo "smiletothesky1970@yahoo.com"
	echo "qnguyen2@utk.edu"
	echo
	echo "Thank you"
	echo
	enter
}

water ()
{	echo "You've selected to donate to this project, Charity Water"
	echo "Please keep in mind that this is completely optional"
	echo "Please at least make yourself aware of the conditions around the globe"
	echo "I should state that I am not trying to exert my opinions or beliefs onto you. This is optional Thank you."
	echo
	enter
	firefox http://www.charitywater.org/
}

#donate
donate ()
{	echo "You've selected to donate to this project, Android Utility"
	echo "Please keep in mind that this is completely optional"
	echo "I do not do this for a living but rather a hobby"
	echo "And my goal is to only assist the pros and rookies"	
	echo "I hope these goals are met. Thank you."
	echo
	echo "PayPal Donation: smiletothesky1970@yahoo.com"
	echo
	enter
	firefox http://bit.ly/r6qjP2
}

clear
VERS=b-1.0.0
echo "|--------------------------------|"
echo "|             Extras             |"
echo "|--------------------------------|"
echo "|--------------------------------|"
echo "|  1.  Check for Updates         |"
echo "|--------------------------------|"
echo "|  2.  contact tommytomatoe      |"
echo "|--------------------------------|"
echo "|  3.  Donate to Charity Water   |"
echo "|--------------------------------|"
echo "|  4.  Donate to project AU      |"
echo "|--------------------------------|"
echo "|--------------------------------|"
echo "   q. Go Back to Main Menu      "
echo
printf %s "Select an Option: "
read num
case $num in
 1) clear; check_u; extras;;
 2) clear; contact_t; extras;;
 3) clear; water; extras;;
 4) clear; donate; extras;;
 q) clear; exit;;
 *) echo; echo "Not a Valid Option" ; echo; enter; zipped_up;;
esac

