#! /bin/bash

# Resources Compression Script
# Author: Tommy Nguyen [tommytomatoe]
# Version: 1.0.3
# Date: October 05, 2011
# Contact: tommytomatoe@gmail.com

# Functions

#enter
enter()
{	echo
	echo -n "Please press [enter] when ready ";
	read -s -n 1 key
	if [[ $key = "" ]]; then 
  		echo &>/dev/null
	fi
}

#load
load_dot ()
{	for r in . . . . . .
	do
	echo -n $r
	sleep .1
	done
	echo "."
}

#quitEND SCRIPT
quit()
{	echo
	echo "Thank you for choosing Android Utility"
	echo "brought to you by tommytomatoe :-)"
	echo
	echo "Please Don't Drink and Drive"
	sleep .25
	clear
	exit
}

res_it ()
{
cd $e	
LOG=FALSE
for F in *.apk ; do
echo "Decompressing resources.arsc in $F"
cd $e
unzip -o $F resources.arsc &>/dev/null
zip -0m $F resources.arsc
if [[ "$?" -ne "0" ]] ; then
	echo "On `date +%b%e_%H%M%S`, $F was not decompressed Properly" >> $HOME/android-utility/log/res_log
	echo "Please check res_log"
	LOG=TRUE	
else
	echo "$F Decompressed"
fi
done
if [[ "$LOG" = "true" ]] ; then
	echo
	echo "Please check res_log for apk with errors"
fi

if ! [[ -s $d/decompressed_res ]] ; then
	mkdir $d/decompressed_res
fi
echo
cd $e
for i in *.apk ; do
	cp -f $i $d/decompressed_res/
	echo "$i is now in decompressed_res"	
done
echo
load_dot
echo
echo -n "Would you like to auto-zipalign at this time? [Y/n] "
read -s -n 1 ans
case $ans in
n|N) echo ; echo ; echo "Cancelling zipalignment" ;;
*) echo ; zipo ;;
esac
}

zipo ()
{
if [[ -s $d/temp ]] ; then
	echo &>/dev/null
else
	mkdir $d/temp
fi
cd $d/decompressed_res
echo
echo "Preparing to zipalign `ls | grep -c .apk` apk files"
echo
load_dot
echo
for z in *.apk ; do
	zipalign -fv 4 $z $d/temp/$z
	mv -f $d/temp/$z $d/decompressed_res
done
rm -r $d/temp
echo
load_dot
clear
echo
cd $d/decompressed_res
echo "Successfully zipaligned `for F in *.apk ; do zipalign -cv 4 $F ; done | grep -c "Verification succesful"` apk files. Congrats!"
echo "Failed to zipalign `for F in *.apk ; do zipalign -cv 4 $F ; done | grep -c "Verification FAILED"` apk files."
}

clear
d=$HOME/android-utility/working-folder/mod-here-multi
e=$d/original_apps
cd $d
echo "Welcome to Resources.arsc Compression Manager"
echo
echo "Please Place apks in $d/original_apps"
	if [[ -s original_apps ]] ; then
		echo &>/dev/null
	else
		mkdir original_apps
	fi
enter
echo
echo "Preparing to decompress resources.arsc"
echo
res_it
echo
echo "Apks have their resources.arsc decompressed for less stress on RAM"
echo
echo "Find new apks in decompressed_res"
enter
quit

