#! /bin/bash

# Rom Utility Linux
# Author: Tommy Nguyen [tommytomatoe]
# Version: 1.0.2
# Date: August 23, 2011
# Contact: tommytomatoe@gmail.com



##functions
#enter
enter()
{	echo
	echo "Please press [enter] to continue";
	read -s -n 1 key
	if [[ $key = "" ]]; then 
  		echo
  		clear
	fi
}


#future features
ff ()
{	clear
	echo "Feature coming in a future release. Stay tuned."
	enter
}



#load
load_dot ()
{	for DOT in . . . . . . . ; do
	echo -n "$DOT"
	sleep .15
	done
	echo "."
}

odex_script ()
{	clear
	echo "Please be aware that this option has only"
	echo "been tested on the HTC EVO 3D Shooter"
	echo
	echo "Might be compatible with other Sense 3.0 Gingerbread Roms and Devices"
	echo "Please use with caution..."
	enter
	3vodex
}



romutil_script () 
{
clear
echo
echo "Welcome to AU ROM Utility"
echo
echo "|-------------------------------|"
echo "|-------------------------------|"
echo "| 1.  Deodex                    |"
echo "| 2.  Dex Optimize [Odex]       |"
echo "| 3.  Signature Categorize      |"
echo "| 4.  Font Changer              |"
echo "| 5.  Boot.img Tool             |"
echo "| 6.  More Later                |"
echo "|-------------------------------|"
echo "| q.  Go to main menu           |"
echo "|-------------------------------|"
echo "|-------------------------------|"
printf %s " Select an Option: "
read num
case $num in
 1) ff;;
 2) odex_script;;
 3) ff;;
 4) ff;;
 5) ff;;
 q) clear; exit;;
 *) echo; echo "$num is not a valid option"; enter;
esac
}

while :
do
	romutil_script
done
