#! /bin/bash

# Android Debug Script Script Linux
# Author: Tommy Nguyen [tommytomatoe]
# Version: b-0.89
# Date: July 08, 2011
# Contact: tommytomatoe@gmail.com

##FUNCTIONS

#enterKey
enterKey()
{	echo "Press [enter] or [space] to $COM, any other key to quit";
	read -s -n 1 key
	if [[ $key = "" ]]; then 
  		echo "Initiating..."
		echo
	else
  		echo "Command not executed";
		enter
	fi
}

#enter
enter()
{	echo "Please press [enter] to continue";
	read -s -n 1 key
	if [[ $key = "" ]]; then 
  		adb_script
	fi
}

#error
error()
{	echo "## Error while processing command"
	echo
}

#error1
error1()
{	echo "## Error while processing command: Please specify valid file name or directory"
	echo
}

#User Decline
user_d()
{	echo "## Error while processing command: User declined"
	echo
}

#load
load()
{	echo -n "   ."
	sleep .125
	echo -n ".."
	sleep .125
	echo -n ".."
	sleep .125
	echo ".."
	sleep .125
	echo -n "    ."
	sleep .125
	echo -n ".."
	sleep .125
	echo -n ".."
	sleep .125
	echo ".."
	sleep .125
	echo -n "     ."
	sleep .125
	echo -n ".."
	sleep .125
	echo -n ".."
	sleep .125
	echo ".."
	sleep .125
}

#load back
daol()
{	echo -n "    ."
	sleep .125
	echo -n ".."
	sleep .125
	echo -n ".."
	sleep .125
	echo ".."
	sleep .125
}

#loader
loader()
{	daol
	load	
	daol
	load
	daol
	load
	daol
	load
	daol
	load
	daol
	load
	daol
	echo
	sleep .5
	echo "    ......."
	echo
	sleep .5
	echo "     ....."
	echo
	sleep .5
	echo "      ..."
	echo
	sleep .5
	echo "       ."
}

#adb remount
adb_rem()
{	clear;
	COM="adb remount"
	echo
	echo "Remounting device as R/W";
	echo
	enterKey
	adb remount
	echo
	enter
}

#adb pull
adb_pull()
{	clear
	COM="adb pull"
	enterKey
	printf "[adb pull] from which directory? [ie. /system/app/] = "
	read DIR
	echo
	printf "[adb pull] which file? [ie. Rosie.apk] = "
	read NAM
	echo
	for a in "adb pull $DIR$NAM $d"
	do
	if [ -e "$d$NAM" ] ; then
		echo "Overwrite existing $NAM? [Y/n] [default=Y]"
		echo
		read -s -n 1 ans
		case "$ans" in
		y|Y) $a;;
		n|N) user_d;;
		*) $a;;
		esac
	else
		$a;
	fi
	done
	if [[ "$NAM" == "" ]] ; then
		error
	fi
	enter
}


#adb shell stop
adb_stop()
{	COM="stop device"
	echo
	enterKey
	echo "Stopping device process"
	adb shell stop
	enter
}

#adb shell start
adb_sta()
{	COM="start device"
	echo
	enterKey
	echo "Starting device"
	adb shell start
	enter
}

#adb devices
adb_dev()
{	COM="list device info"
	echo
	enterKey
	echo
	echo "Gathering information about your device"
	echo
	adb devices
	enter
}

#adb reboot
adb_r()
{	COM="adb reboot"
	echo
	enterKey
	echo
	echo "Rebooting Device"
	adb reboot
	enter
}
	
#adb reboot recovery
adb_re()
{	COM="adb reboot to recovery"
	echo
	enterKey
	echo "Rebooting Device"
	adb reboot recovery
	enter
}

#adb reboot bootloader
adb_bl()
{	COM="adb reboot to bootloader"
	echo
	enterKey
	echo "Rebooting Device"
	adb reboot bootloader
	enter
}

#hot restart...kind of
hot_res()
{	COM="hot restart"
	echo
	enterKey
	echo
	echo "Stopping Device "
	adb shell stop
	daol
	adb shell start
	daol
	daol
	daol
	daol
	daol
	echo "Starting Device"
	loader
	sleep 1
	echo
	echo "Device is up and running"
	echo
	enter
}

#adb push
adb_push()
{	clear
	COM="adb push"
	enterKey
	printf %s "[adb push] to which directory? [ie. /system/app/] = "
	read DIR
	echo
	echo "These files are available in $d:"
	echo
	ls -t -1 $d
	echo
	printf %s "[adb push] which file? [ie. Rosie.apk] = "
	read NAM
	for a in "adb push $d$NAM $DIR"
	do
	if [[ "$NAM" == "" ]] ; then
		echo
		error1;
	else
		$a
	fi
	done
	enter
}

#adb install
adb_inst()
{	clear
	COM="adb install"
	enterKey
	echo
	echo "These files are available in $d:"
	echo
	ls -t -1 $d | grep -- .apk
	echo
	printf %s "[adb install] which file? [ie. DataApp.apk] = "
	read INS
	for a in "adb install $d$INS"
	do
	if [[ "$INS" == "" ]] ; then
		echo
		error1;
	else
		$a
	fi
	done
	enter
}
	

#adb shell
adb_shell() 
{	clear
	COM="enter adb shell"
	enterKey
	echo "Remounting R/W"
	adb remount
	sleep 1
	clear
	echo `adb devices`
	echo
	adb shell
}

enter_e()
{	echo "Please press [enter] to continue";
	read -s -n 1 key
	if [[ $key = "" ]]; then 
  		clear
	fi
}


#adb script
adb_script() {
#export PATH
cd $HOME/android-utility/
d="$HOME/android-utility/working-folder/mod-here-multi/"
e="$HOME/android-utility/working-folder/mod-here-solo/"
clear
echo "                   ------------------     "
echo "                  Android Debug Bridge                  "
echo "|--------------------------||--------------------------|"
echo "|    Basic ADB Commands    ||  Advanced ADB Commands   |"
echo "|--------------------------||--------------------------|"
echo "|  1.  remount             ||  7.  pull                |"
echo "|  2.  devices             ||  8.  push                |"
echo "|  3.  reboot              ||  9.  shell               |"
echo "|  4.  reboot recovery     || 10.  shell stop          |"
echo "|  5.  reboot bootloader   || 11.  shell start         |"
echo "|  6.  hot restart         || 12.  install             |"
echo "|                          ||                          |"
echo "|--------------------------||--------------------------|"
echo "|--------------------------||--------------------------|"
echo "|--------------------------||--------------------------|"
echo "     I. Info on Android Debug Commands"
echo "     E. Go to Express Menu (use with 'mod-here-solo')"
echo "     q. Go Back to Main Menu                "
echo "                   ------------------     "
echo
printf "%s" "  Choose an ADB Command: "
read num
case "$num" in
  1)  adb_rem;;
  2)  adb_dev;;
  3)  adb_r;;
  4)  adb_re;;
  5)  adb_bl;;
  6)  hot_res;;
  7)  adb_pull;;
  8)  adb_push;;
  9)  adb_shell;;
 10)  adb_stop;;
 11)  adb_sta;;
 12)  adb_inst;;
 i|I) cat $HOME/android-utility/resources/clean/adb.txt | more;;
 e|E) express_adb;;
  q) clear; exit;;
 *) echo; echo "Please enter valid option"; enter;
esac
}

while :
do
	adb_script
done
