#! /bin/bash

# Zipalign Script Linux
# Author: Tommy Nguyen [tommytomatoe]
# Version: b-0.89
# Date: July 08, 2011
# Contact: tommytomatoe@gmail.com

##FUNCTIONS

#load
load_dot ()
{	echo -n "."
	sleep .15
	echo -n "."
	sleep .15
	echo -n "."
	sleep .15
	echo -n "."
	sleep .15
	echo -n "."
	sleep .15
	echo "."
}

#enterKey
enterKey()
{	echo "Press [enter] or [space] to $COM, any other key to quit";
	read -s -n 1 key
	if [[ $key = "" ]]; then 
  		echo "Initiating..."
		echo
	else
  		echo "Command not executed";
		enter
	fi
}

#enter
enter()
{	echo "Please press [enter] to continue";
	read -s -n 1 key
	if [[ $key = "" ]]; then 
  		echo
	fi
}

#future features
ff ()
{	clear
	echo "Feature coming in a future release. Stay tuned."
	enter
}

#check zipalignment
check_it ()
{	echo "Please place apk[s] in:"
	echo
	echo $n
	echo
	enter
	cd $n
	for a in *.apk; do 
	echo "Checking zipalignment on $a"	
	echo
	$HOME/bin/zipalign -cv 4 $a 
	echo
	done
	enter
}

#zip
zip_it ()
{	echo "Please place apk[s] in:"
	echo
	echo $n
	echo
	enter
	cd $n
	mkdir done_aligned
	for a in *.apk; do 
	echo "Checking zipalignment on $a" 
	echo
	$HOME/bin/zipalign -fv 4 $a done_aligned/$a
	echo
	done
	enter
}

clear
#variables
n=$HOME/android-utility/working-folder/zipalign
if [[ -s $n ]] ; then 
	echo
else
	mkdir $n
fi
p=$HOME/android-utility/working-folder/zipalign/DONE
echo "|--------------------------------|"
echo "|       Zipalign Utilities       |"
echo "|--------------------------------|"
echo "|--------------------------------|"
echo "|  1.  Zipalign apk[s]           |"
echo "|--------------------------------|"
echo "|  2.  Check for Zipalignment    |"
echo "|--------------------------------|"
echo "|  3.  INFO on zipalign          |"
echo "|--------------------------------|"
echo "|--------------------------------|"
echo "   q. Go Back to Main Menu      "
echo
printf %s "Select an Option: "
read num
case $num in
 1) clear; zip_it; zipped_up;;
 2) clear; check_it; zipped_up;;
 3) cat $HOME/android-utility/resources/clean/zipalign.pdf; enter; zipped_up;; 
 q) clear; exit;;
 *) echo; echo "Not a Valid Option" ; echo; enter; zipped_up;;
esac
